'use strict';
const firstName = 'Karina Kim';
const isCool = true;
const totalPets = 1;
console.log('value of fullName:', firstName);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('typeof fullName:', typeof firstName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
const empty = null;
console.log('value of empty:', empty);
console.log('typeof empty:', typeof empty);
const nothing = undefined;
console.log('value of nothing:', nothing);
console.log('typeof nothing:', typeof nothing);
