'use strict';
let colors = ['red', 'white', 'blue'];
console.log('value of colors[0]:', colors[0]);
console.log('value of colors[1]:', colors[1]);
console.log('value of colors[2]:', colors[2]);
const americaIs = `America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(americaIs);
colors[2] = 'green';
const mexicoIs = `Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(mexicoIs);
console.log('value of colors:', colors);
console.log('typeof colors:', typeof colors);
const students = ['Josh', 'Victoria', 'Jared', 'Val'];
const numberOfStudents = students.length;
const studentsInClass = `There are ${numberOfStudents} students in the class.`;
console.log(studentsInClass);
const lastIndex = students.length - 1;
const lastStudent = students[students.length - 1];
const lastStudentIs = `The last student in the array is ${lastStudent}.`;
console.log(lastStudentIs);
console.log('value of students:', students);
console.log('typeof students:', typeof students);
